---
#tasks file for roles/aws-cli

- name: install mkpasswd, pip, pexpect, passlib
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-apt
    - python-pip
    - zip
  vars:
    ansible_python_interpreter: "{{ package_python_interpreter }}"
