#!/bin/bash

set -e

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # The directory of this script

readonly host1="$(aws ec2 describe-tags --filters Name=key,Values=Name Name=value,Values=vault-example Name=resource-type,Values=instance | jq '.Tags[0].ResourceId' --raw-output).node.consul"

echo "Warning: This step is a temporary measure until vault instances can init themselves.  A better workflow is required here for production use since we are not protected against MITM."
echo "we are however in a newly created private subnet, and it is a temporary compromise."
echo "Removing any previous host keys for: $host1"
ssh-keygen -R $host1

ssh -l ubuntu $host1 "bash -s" < "$SCRIPTDIR/initialize-ssh"
