#!/bin/bash

set -e

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # The directory of this script

readonly instanceid="$(aws ec2 describe-tags --filters Name=key,Values=Name Name=value,Values=vault-example Name=resource-type,Values=instance | jq '.Tags[0].ResourceId' --raw-output)"
readonly hostname=$instanceid.node.consul
readonly privateip="$(aws ec2 describe-instances --filters "Name=instance-state-name,Values=running" "Name=instance-id,Values=$instanceid" --query 'Reservations[*].Instances[*].[PrivateIpAddress]' --output text)"

echo "Removing any previous host keys for: $hostname,$privateip"
ssh-keygen -R $hostname
ssh-keygen -R $privateip
echo "Adding hostkeys using AWS CLI query for $hostname,$privateip"
aws ec2 get-console-output --instance-id $instanceid | jq .Output -r |sed -n -e '1,/-----BEGIN SSH HOST KEY KEYS-----/d; /-----END SSH HOST KEY KEYS-----/q; p' | grep ecdsa-sha2-nistp256 | awk -v host=$hostname,$privateip '{ print host " " $1 " " $2 }' | tee --append ~/.ssh/known_hosts

ssh -l ubuntu $hostname "bash -s" < "$SCRIPTDIR/initialize-ssh"
