#!/bin/bash

set -e

if [[ ! -f "/opt/consul/bin/run-consul" ]]; then
    echo "You have not yet installed consul."
    exit 0 # if the user hasn't installed consul yet, this step must be performed manually.
fi

echo "Running Consul..."

output=$(sudo /opt/consul/bin/run-consul --client --cluster-tag-key "${consul_cluster_tag_key}" --cluster-tag-value "${consul_cluster_tag_value}") && exit_status=0 || exit_status=$?

if [[ ! "$exit_status" -eq 0 ]]; then
    echo "Error establishing consul connection.  Ensure the SSL certs are correct, and instance profile is configured and enabled in cloud 9 prefs."
else
    echo "$output"
fi
