#!/bin/bash

set -e

echo ""
echo "Warning: creating an admin token and using it to login.  You should only ever run this script once."
echo ""

admin_token=$(vault token create -policy=admins -policy=vpn_read_config -explicit-max-ttl=720h -field=token)
vault login --no-print $admin_token