---

- hosts: "{{ variable_host | default('ansible_control') }}"
  remote_user: "{{ variable_connect_as_user | default('deployuser') }}"
  gather_facts: "{{ variable_gather_facts | default('false') }}"
  become: true

  vars:
    variable_user: deadlineuser
    variable_uid: 9001
    variable_user_gid: "{{ variable_uid }}"
    variable_gid: "{{ syscontrol_gid }}"
    my_password: "{{ user_deadlineuser_pw | string | password_hash('sha512') }}"
    no_extension: "{{ deadline_linux_installers_tar | splitext | first }}"
    basename: "{{ no_extension.split('/')[-1] }}"
    houdini_major_version: 18.0
  
  pre_tasks:
  - name: test connection as deployuser
    debug:
      msg: "connection established"

  - name: Collect some facts only for ansible_distribution
    setup:
      gather_subset:
        - '!all'
        - 'min'
    tags:
    - always

  roles:
  - role: 'add-user-to-group'
    vars:
      variable_group: 'syscontrol'

  tasks:
  - name: reset ssh connection to allow user changes to affect 'current login user'
    meta: reset_connection