- hosts: firehawkgateway
  remote_user: deployuser
  gather_facts: "{{ variable_gather_facts | default('false') }}"
  become: true

  vars:
    client_network: None
    client_netmask_bits: None

  pre_tasks:
  - name: force systemd to restart openvpn client
    systemd:
      name: openvpn
      state: restarted