- hosts: "{{ variable_host | default('ansible_control') }}"
  become: true
  remote_user: "{{ variable_user | default('deployuser') }}"
  gather_facts: "{{ variable_gather_facts | default('false') }}"

  vars:
    variable_user: deployuser

  roles:
  - {role: 'pgp-decrypt-test'}