- hosts: "{{ variable_host | default('localhost') }}"
  remote_user: "{{ variable_user | default('deployuser') }}"
  become: true
  gather_facts: "{{ variable_gather_facts | default('false') }}"

  vars:
    bastion_ip: false
    local: false
    variable_user: deployuser

  roles:
  - ssh-add-private-host