- hosts: ansible_control
  remote_user: deployuser
  gather_facts: "{{ variable_gather_facts | default('false') }}"
  become: true

  tasks:
    - name: test update
      debug:
        msg: "test local connection"