- name: create blank keys dir if it doesn't exist
  file:
    path: "{{ key_folder }}"
    state: directory

- name: create blank vault if it doesn't exist
  file:
    path: "{{ key_path }}"
    state: touch
    access_time: preserve
    modification_time: preserve