#!/bin/bash
set -e

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # The directory of this script

source $SCRIPTDIR/update_vars.sh

cd $SCRIPTDIR/modules/terraform-aws-vault-client
export TF_VAR_vault_client_ami_id=none
terraform plan -out=tfplan -input=false -destroy
terraform apply -input=false tfplan

cd $SCRIPTDIR/modules/terraform-aws-bastion
export TF_VAR_bastion_ami_id=none
terraform plan -out=tfplan -input=false -destroy
terraform apply -input=false tfplan

cd $SCRIPTDIR/modules/vault
terraform plan -out=tfplan -input=false -destroy
terraform apply -input=false tfplan
# terraform destroy --auto-approve -input=false $SCRIPTDIR/modules/vault # Destroy vault instances. Data is persisted to S3.

cd $SCRIPTDIR/modules/vpc
terraform plan -out=tfplan -input=false -destroy
terraform apply -input=false tfplan # Stop bastion hosts.