#!/bin/bash
set -e

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # The directory of this script

source $SCRIPTDIR/update_vars.sh

cd $SCRIPTDIR/deployments/vault
terraform plan -out=tfplan -input=false -destroy
terraform apply -input=false tfplan
# terraform destroy --auto-approve -input=false $SCRIPTDIR/deployments/vault # Destroy vault instances. Data is persisted to S3.

cd $SCRIPTDIR
terraform plan -out=tfplan -input=false -var "sleep=true"
terraform apply -input=false tfplan # Stop bastion hosts.