#!/bin/bash
set -e

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # The directory of this script

source $SCRIPTDIR/update_vars.sh
terraform destroy --auto-approve $SCRIPTDIR/deployments/vault # Destroy vault instances. Data is persisted to S3.
terraform apply -var "sleep=true" --auto-approve # Stop bastion hosts.