#!/bin/bash
set -e

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # The directory of this script

source $SCRIPTDIR/update_vars.sh

cd $SCRIPTDIR/deployments/vault
terraform init -input=false
terraform plan -out=tfplan -input=false
terraform apply -input=false tfplan --auto-approve # Start vault instances

cd $SCRIPTDIR
terraform init -input=false
terraform plan -out=tfplan -input=false
terraform apply -input=false tfplan --auto-approve # Start bastion hosts.