#!/bin/bash
set -e

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # The directory of this script

source $SCRIPTDIR/update_vars.sh

cd $SCRIPTDIR/modules/vpc
terraform init \
    -input=false \
    -backend-config="bucket=state.terraform.$TF_VAR_bucket_extension" \
    -backend-config="key=main/vpc/terraform.tfstate" \
    -backend-config="region=$AWS_DEFAULT_REGION" \
    -backend-config="dynamodb_table=locks.state.terraform.$TF_VAR_bucket_extension"
terraform plan -out=tfplan -input=false -var "sleep=true"
terraform apply -input=false tfplan # Ensure Main VPC exists

cd $SCRIPTDIR/modules/vault
./generate-plan
terraform apply -input=false tfplan # Start Vault / Consul instances, and configure VPC peering with the current cloud 9 VPC.

cd $SCRIPTDIR/modules/vpc
# ./s3-backend-template/generate-s3-backend
terraform init -input=false
terraform plan -out=tfplan -input=false
terraform apply -input=false tfplan # Start bastion hosts in Main VPC after the servers for immedite connection to consul service discovery