- name: "echo bastion public ip before connecting as user {{ variable_user }}. If the next stage cannot connect its possible ssd authorized_keys file has not been configured / initalised correctly on the host.  This can occur if the VM machine state was not saved after init"
  debug:
    msg: "{{ item }}"
  with_items:
    - "{{ public_ip }}"
    
- file:
    path: "/home/{{ variable_user }}/.ssh/known_hosts"
    state: touch
  become_user: "{{ variable_user }}"
  
- name: clean known hosts
  shell: "ssh-keygen -R {{ public_ip }} -f /home/{{ variable_user }}/.ssh/known_hosts"
  become: true
  become_user: "{{ variable_user }}"

- name: clean known hosts
  shell: "ssh-keygen -R {{ public_address }} -f /home/{{ variable_user }}/.ssh/known_hosts"
  become: true
  become_user: "{{ variable_user }}"
  