- name: Get files in a folder /opt/Thinkbox/DeadlineDatabase10/mongo/data/logs/
  find:
    paths: "/opt/Thinkbox/DeadlineDatabase10/mongo/data/logs/"
  register: found_files
  no_log: true

- name: Get latest file
  set_fact:
    latest_file: "{{ found_files.files | sort(attribute='mtime',reverse=true) | first }}"

- name: "Get file {{ latest_file.path }} copy to {{ firehawk_path }}/tmp/{{ out_file }}"
  fetch:
    src: "{{ latest_file.path }}"
    dest: "{{ firehawk_path }}/tmp/log/{{ out_file }}"
    flat: yes
    validate_checksum: no # logs may have incorrect checksums, possibly since data changes rapidly after download.
  become: true

- name: 'Get all files: file {{ item.path }} copy to {{ firehawk_path }}/tmp/'
  fetch:
    src: "{{ item.path }}"
    dest: "{{ firehawk_path }}/tmp/log/"
    flat: yes
    validate_checksum: no # logs may have incorrect checksums, possibly since data changes rapidly after download.
  become: true
  with_items: "{{ found_files.files }}"
  no_log: true