# Do not directly edit this in the firehawk repository.  Instead, create a copy located at secrets/dev/ebs-volumes to override it

mounts:
# these are mounts for ebs volumes to the softnas instance.
- path: "/dev/sdb"
  int: "1"
  ebs_disk_type: gp2
  ebs_disk_size: 20
  pool_name: "{{ resourcetier }}pool1"
  volatile: "{{ softnas_volatile }}"
- path: "/dev/sdc"
  int: "2"
  ebs_disk_type: gp2
  ebs_disk_size: 20
  pool_name: "{{ resourcetier }}pool1"
  volatile: "{{ softnas_volatile }}"

exports:
- path: "/{{ resourcetier }}pool1/{{ resourcetier }}volume1" # production volume - Softnas
  pool_name: "{{ resourcetier }}pool1"
  volume_name: "{{ resourcetier }}volume1"
  raid_level: 0
  state: present
  bind1: "{{ prod_path_generic }}"
  bind2: "{{ prod_path_abs_cloud }}"
  site_bind1:

# this volume is another medium performance production disk. if used, you must also define mounts/disks above
# - path: "/{{ envtier }}pool2/{{ envtier }}volume2/"
#   pool_name: "{{ envtier }}pool2"
#   volume_name: "{{ envtier }}volume2"
#   raid_level: 6
#   state: present
#   bind1: "/volatile/"
#   bind2: "/aws_sydney_volatile/"