#!/bin/bash
set -e

exit_if_error() {
  local exit_code=$1
  shift
  [[ $exit_code ]] &&               # do nothing if no error code passed
    ((exit_code != 0)) && {         # do nothing if error code is 0
      printf 'ERROR: %s\n' "$@" >&2 # we can use better logging here
      exit "$exit_code"             # we could also check to make sure
                                    # error code is numeric when passed
    }
}

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # The directory of this script

cd ../terraform-aws-iam-s3; terraform output
vault_client_role_arns

export TF_VAR_vault_client_role_arns=["$(cd ../terraform-aws-iam-s3; terraform output -json "provisioner_instance_role_arn" | jq -r '.')"]

terraform apply "tfplan" -input=false