#!/bin/bash

set -e

if [[ -z "$VAULT_TOKEN" ]]; then
    echo "Instances from this point require you to login to vault.  To avoid this message you can define the var VAULT_TOKEN"
fi

echo "Waiting for consul vault service..."
until consul catalog services | grep -m 1 "vault"; do sleep 1 ; done
until vault status | grep -m 1 "Initialized.*"; do sleep 1 ; done

initialised=true
vault status | grep -m 1 "Initialized.*true" || initialised=false

if [[ "$initialised" == false ]]; then
    echo "Vault is not Initialized.  Aborting. You will need to login and initialise the vault"
    exit 1
fi
sleep 10

# Why?
# vault token lookup
# Error looking up token: Error making API request.
# URL: GET https://vault.service.consul:8200/v1/auth/token/lookup-self
# Code: 500. Errors:

echo "vault token lookup"

output=$(vault token lookup) && exit_status=0 || exit_status=$?
errors=$(echo "$output") | grep '^{' | jq -r .errors
echo "$output"
if [[ $exit_status -eq 0 && -z "$errors" ]]; then
    echo "$output"
else
    echo "...logging in. Or exit and use: vault login --no-print"
    vault login --no-print $VAULT_TOKEN
fi
vault token lookup