- hosts: localhost
  user: deployuser
  gather_facts: "{{ variable_gather_facts | default('false') }}"
  sudo: yes

  tasks:
    - name: change hostname to myserver
      hostname:
        name: "{{ openfirehawkserver_name }}"
    - name: add myself to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.0\.1[ \t]+localhost'
        line: "127.0.0.1 localhost {{ openfirehawkserver_name }}"
        state: present
