- hosts: localhost
  user: deployuser
  gather_facts: "{{ variable_gather_facts | default('false') }}"
  sudo: yes

  tasks:
    - name: install mkpasswd
      package:
        name:
        - whois
        - python-pip
        state: present
      vars:
        ansible_python_interpreter: "{{ package_python_interpreter }}"

    - name: install pexpect
      pip:
        name: pexpect
      become: yes
      
    - name: install passlib
      pip:
        name: passlib
      become: yes