#!/bin/bash
set -e

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # The directory of this script

envsubst < $SCRIPTDIR/template/s3-backend.tf > $SCRIPTDIR/s3-backend.tf