AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  Shared parameters for a firehawk deployment.

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Network Configuration"
        Parameters: 
          - resourcetier
          - organizationname
          - validityperiodhours
          - combinedvpcscidr
          - onsitepublicip
          - onsiteprivatesubnetcidr
          - vpncidr
          - globalbucketextension
          - ublurl
          - ublactivationcode
          - houdinilicenseserveraddress
          - sesiclientid
          - sesiclientsecretkey
    ParameterLabels: 
      resourcetier: 
        default: "Deployment Environment (resourcetier)"
      organizationname:
        default: "The name of the organization to associate with certificates (e.g. My Company)"
      validityperiodhours:
        default: "The validity period for the Vault/Consul SSL Certificate Authority (CA) in hours"
      combinedvpcscidr: 
        default: "The CIDR Range containing all cloud resource."
      onsitepublicip:
        default: "Your Public IP Address onsite will be used for configuring security groups."
      onsiteprivatesubnetcidr:
        default: "Your onsite private subnet CIDR range is used to configure routing with Open VPN."
      vpncidr:
        default: "The CIDR range Open VPN will use internally for routing"
      globalbucketextension:
        default: "Your Global Bucket Extension."
      ublurl:
        default: "Your Deadline Usage Based Licensing URL."
      ublactivationcode:
        default: "Your Deadline Usage Based Licensing activation code."
      houdinilicenseserveraddress:
        default: "Your Houdini License Server IP Address."
      sesiclientid:
        default: "You Side FX Account API Client ID."
      sesiclientsecretkey:
        default: "You Side FX Account API Secret Key"

Parameters:
  resourcetier:
    Description: 'The resource tier uniquely defining the deployment area.  eg: dev/green/blue/main.'
    Type: String
    AllowedValues:
    - dev
    - green
    - blue
    - main
    Default: main
  organizationname:
    Description: 'The organization name will be used to associate with generated certificates'
    Type: String
    AllowedPattern: "[a-zA-Z0-9 ]*"
  validityperiodhours:
    Description: 'The Root CA and AMI images will expire after this TTL (Time To Live) period.'
    Type: String
    AllowedPattern: "[0-9]*"
    Default: 8760
  combinedvpcscidr:
    Description: 'The IP range used for the main and rendering VPCs.  Cloud hosts will reside within this range and it must not intersect with your private network range. eg: 10.4.0.0/16 will not interfer with 192.168.1.0/24'
    Type: String
    Default: "10.4.0.0/16"
    AllowedPattern: "^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\\/([1-2][0-9]|3[0-2]))?$"
  onsitepublicip:
    Description: 'The public IP of your onsite connection used to connect to the cloud infra. Google "what is my ip" for the value. If you do not have a static IP, Terraform may need to update more frequently.'
    Type: String
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$"
  onsiteprivatesubnetcidr:
    Description: 'The private subnet IP range used for your onsite hosts.  Your router will usually use DHCP to place hosts within this range. eg: 192.168.29.0/24'
    Type: String
    AllowedPattern: "^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\\/([1-2][0-9]|3[0-2]))?$"
  vpncidr:
    Description: 'The IP range open VPN will use internally for routing.  The default should be fine for most purposes. eg: 172.20.232.0/24'
    Type: String
    Default: "172.20.232.0/24"
    AllowedPattern: "^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\\/([1-2][0-9]|3[0-2]))?$"
  sesiclientid:
    Description: 'The client secret key generated from your Side FX Account to automatically download Houdini.'
    Type: String
  sesiclientsecretkey:
    NoEcho: true
    Description: 'The client ID generated from your Side FX Account to automatically download Houdini.'
    Type: String
  houdinilicenseserveraddress:
    Description: 'The IP or host name of your Houdini license server (IP Address is recommended to simplify usage across sites with DNS).'
    Type: String
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$"
  globalbucketextension:
    Description: 'The suffix used for all S3 cloud storage buckets created by the deployment and for encrypted terraform state.  This must be a globally unique name, like a domain name you own, or derived from an email addess with no special characters. eg1: example.com  eg2: myemailatgmaildotcom'
    Type: String
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-.]*[0-9a-zA-Z])*$"
    ConstraintDescription: bucket name can include numbers, lowercase letters, uppercase letters, dots (.) and hyphens (-). It cannot start or end with a dot (.) or hyphen (-).
  ublurl:
    Description: 'The URL provided by Thinkbox for your Usage Based Licencing credits.  Rendernodes on AWS get deadline free, but if you require UBL software licences for other packages or for your onsite workstations you will need to purchase credits.'
    Type: String
    AllowedPattern: "^https.*"
    ConstraintDescription: URL should start with https://thinkbox.compliance.flexnetoperations.com
  ublactivationcode:
    NoEcho: true
    Description: 'The 16 digit activation code provided by Thinkbox for your usage based licencing. eg: 3JNF-V8B7-3JDN-48GN'
    Type: String
    AllowedPattern: "^.{19}$"
    ConstraintDescription: The provided string must be 16 digits.
Resources:
  SSMCombinedVPCCIDR:
    Type: AWS::SSM::Parameter
    Properties:
      Name: 
        Fn::Join:
        - ''
        - - '/firehawk/resourcetier/'
          - Ref: resourcetier
          - /combined_vpcs_cidr
      Type: String
      Value: !Ref combinedvpcscidr
      Description: 'The IP range used for the main VPC.'
  SSMOrganizationName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: 
        Fn::Join:
        - ''
        - - '/firehawk/resourcetier/'
          - Ref: resourcetier
          - /organization_name
      Type: String
      Value: !Ref organizationname
      Description: 'The organization name to associate with certificates.'
  SSMValidityPeriodHours:
    Type: AWS::SSM::Parameter
    Properties:
      Name: 
        Fn::Join:
        - ''
        - - '/firehawk/resourcetier/'
          - Ref: resourcetier
          - /validity_period_hours
      Type: String
      Value: !Ref validityperiodhours
      Description: 'The Certificate TTL in hours.'
  SSMOnsitePublicIp:
    Type: AWS::SSM::Parameter
    Properties:
      Name: 
        Fn::Join:
        - ''
        - - '/firehawk/resourcetier/'
          - Ref: resourcetier
          - /onsite_public_ip
      Type: String
      Value: !Ref onsitepublicip
      Description: 'The public IP of your onsite connection used to connect to the cloud infra. Google "what is my ip" for the value. If you do not have a static IP, Terraform may need to update more frequently.'
      AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$"
  SSMOnsitePrivateSubnetCIDR:
    Type: AWS::SSM::Parameter
    Properties:
      Name: 
        Fn::Join:
        - ''
        - - '/firehawk/resourcetier/'
          - Ref: resourcetier
          - /onsite_private_subnet_cidr
      Type: String
      Value: !Ref onsiteprivatesubnetcidr
      Description: 'The private subnet IP range used for your onsite hosts.  Your router will usually use DHCP to place hosts within this range. eg: 192.168.29.0/24'
      # AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-3]|[0-9]))$"
  SSMVPNCIDR:
    Type: AWS::SSM::Parameter
    Properties:
      Name: 
        Fn::Join:
        - ''
        - - '/firehawk/resourcetier/'
          - Ref: resourcetier
          - /vpn_cidr
      Type: String
      Value: !Ref vpncidr
      Description: 'The IP range open VPN will use internally for routing.  The default should be fine for most purposes. eg: 172.20.232.0/24'
  GlobalBucketExtension:
    Type: AWS::SSM::Parameter
    Properties:
      Name: 
        Fn::Join:
        - ''
        - - '/firehawk/resourcetier/'
          - Ref: resourcetier
          - /global_bucket_extension
      Type: String
      Value: !Ref globalbucketextension
      Description: 'The suffix used for all S3 cloud storage buckets created by the deployment and for encrypted terraform state.  This must be a globally unique name, like a domain name you own, or derived from an email addess with no special characters. eg1: example.com eg2: myemailatgmaildotcom'
      AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-.]*[0-9a-zA-Z])*$"
# Deadline UBL Licensing
  UsageBasedLicenseURL:
    Type: AWS::SSM::Parameter
    Properties:
      Name: 
        Fn::Join:
        - ''
        - - '/firehawk/resourcetier/'
          - Ref: resourcetier
          - /ubl_url
      Type: String
      Value: !Ref ublurl
      Description: 'The URL provided by Thinkbox for your Usage Based Licencing credits.  Rendernodes on AWS get deadline free, but if you require UBL software licences for other packages or for your onsite workstations you will need to purchase credits.'
      AllowedPattern: "^https.*"
  UsageBasedLicenseActivationCode:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: 
        Fn::Join:
        - ''
        - - '/firehawk/resourcetier/'
          - Ref: resourcetier
          - /ubl_activation_code
      SecretString: !Ref ublactivationcode
      Description: 'The 16 digit activation code provided by Thinkbox for your usage based licencing.'
# For Houdini
  SSMHoudiniLicenseServerAddress:
    Type: AWS::SSM::Parameter
    Properties:
      Name: 
        Fn::Join:
        - ''
        - - '/firehawk/resourcetier/'
          - Ref: resourcetier
          - /houdini_license_server_address
      Type: String
      Value: !Ref houdinilicenseserveraddress
      Description: 'The IP or host name of your Houdini license server (IP Address is recommended to simplify usage across sites with DNS).'
      AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$"
  SSMSESIClientID:
    Type: AWS::SSM::Parameter
    Properties:
      Name: 
        Fn::Join:
        - ''
        - - '/firehawk/resourcetier/'
          - Ref: resourcetier
          - /sesi_client_id
      Type: String
      Value: !Ref sesiclientid
      Description: 'The client ID generated from your Side FX Account to automatically download Houdini.'
  SSMSESIClientSecretKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: 
        Fn::Join:
        - ''
        - - '/firehawk/resourcetier/'
          - Ref: resourcetier
          - /sesi_client_secret_key
      SecretString: !Ref sesiclientsecretkey
      Description: 'The client secret key generated from your Side FX Account to automatically download Houdini.'