# further changes are required for this to be used.  We need to restrict the access to the key to a profile / vpc that the vault instamces will use.
# https://docs.aws.amazon.com/kms/latest/developerguide/kms-vpc-endpoint.html#vpce-policy

myKey:
  Type: AWS::KMS::Key
  Properties:
    Description: An example symmetric CMK
    KeyPolicy:
      Version: '2012-10-17'
      Id: key-default-1
      Statement:
      - Sid: Enable IAM User Permissions
        Effect: Allow
        Principal:
          AWS:
            Fn::Join:
            - ''
            - - 'arn:aws:iam::'
              - Ref: AWS::AccountId
              - :root
        Action: kms:*
        Resource: '*'
      - Sid: Allow administration of the key
        Effect: Allow
        Principal:
          AWS:
            Fn::Join:
            - ''
            - - 'arn:aws:iam::'
              - Ref: AWS::AccountId
              - :user/andrewgr
        Action:
        - kms:Create*
        - kms:Describe*
        - kms:Enable*
        - kms:List*
        - kms:Put*
        - kms:Update*
        - kms:Revoke*
        - kms:Disable*
        - kms:Get*
        - kms:Delete*
        - kms:ScheduleKeyDeletion
        - kms:CancelKeyDeletion
        Resource: '*'
      - Sid: Allow use of the key to all users.  This should be further restricted.
        Effect: Allow
        Principal:
          AWS:
            Fn::Join:
            - ''
            - - 'arn:aws:iam::'
              - Ref: AWS::AccountId
              - :user/*
        Action:
        - kms:DescribeKey
        - kms:Encrypt
        - kms:Decrypt
        - kms:ReEncrypt*
        - kms:GenerateDataKey
        - kms:GenerateDataKeyWithoutPlaintext
        Resource: '*'